package com.dcsh.market;

// Generated 2009-3-2 20:48:10 by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Canku generated by hbm2java
 */
@Entity
@Table(name = "Canku", schema = "dbo", catalog = "test")
public class Canku implements java.io.Serializable {

	private int id;
	private String name;
	private byte type;
	private String address;
	private Set<Chuku> chukusForRkId = new HashSet<Chuku>(0);
	private Set<Chuku> chukusForCankuId = new HashSet<Chuku>(0);
	private Set<Rkxx> rkxxes = new HashSet<Rkxx>(0);

	public Canku() {
	}

	public Canku(int id, String name, byte type) {
		this.id = id;
		this.name = name;
		this.type = type;
	}

	public Canku(String name, byte type) {
		this.name = name;
		this.type = type;
	}

	public Canku(int id, String name, byte type, String address,
			Set<Chuku> chukusForRkId, Set<Chuku> chukusForCankuId,
			Set<Rkxx> rkxxes) {
		this.id = id;
		this.name = name;
		this.type = type;
		this.address = address;
		this.chukusForRkId = chukusForRkId;
		this.chukusForCankuId = chukusForCankuId;
		this.rkxxes = rkxxes;
	}

	@Id @GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "Name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Type", nullable = false)
	public byte getType() {
		return this.type;
	}

	public void setType(byte type) {
		this.type = type;
	}

	@Column(name = "Address", length = 100)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "cankuByRkId")
	public Set<Chuku> getChukusForRkId() {
		return this.chukusForRkId;
	}

	public void setChukusForRkId(Set<Chuku> chukusForRkId) {
		this.chukusForRkId = chukusForRkId;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "cankuByCankuId")
	public Set<Chuku> getChukusForCankuId() {
		return this.chukusForCankuId;
	}

	public void setChukusForCankuId(Set<Chuku> chukusForCankuId) {
		this.chukusForCankuId = chukusForCankuId;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "canku")
	public Set<Rkxx> getRkxxes() {
		return this.rkxxes;
	}

	public void setRkxxes(Set<Rkxx> rkxxes) {
		this.rkxxes = rkxxes;
	}

    public int hashCode() {
    	return this.getId();
    }
    
    @Override
    public boolean equals(Object obj){
    	if(obj instanceof Canku){
    		Canku ck = (Canku)obj;
    		return this.getId() == ck.getId();
    	}
    	return false;
    }
}
