package com.dcsh.market;

// Generated 2009-3-2 20:48:10 by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Chukumx generated by hbm2java
 */
@Entity
@Table(name = "Chukumx", schema = "dbo", catalog = "test")
public class Chukumx implements java.io.Serializable {

	private int id;
	private Products products;
	private Chuku chuku;
	private Specifications specifications;
	private String pch;
	private int number;
	private byte status;//表示此批货物出库状态，0表示在途，1表示到货

	public Chukumx() {
	}

	public Chukumx(int id, Products products, Chuku chuku,
			Specifications specifications, String pch, int number) {
		this.id = id;
		this.products = products;
		this.chuku = chuku;
		this.specifications = specifications;
		this.pch = pch;
		this.number = number;
	}

	public Chukumx(Products products, Chuku chuku,
			Specifications specifications, String pch, int number) {
		this.products = products;
		this.chuku = chuku;
		this.specifications = specifications;
		this.pch = pch;
		this.number = number;
	}
	
	

	public Chukumx(Products products, Chuku chuku,
			Specifications specifications, String pch, int number, byte status) {
		super();
		this.products = products;
		this.chuku = chuku;
		this.specifications = specifications;
		this.pch = pch;
		this.number = number;
		this.status = status;
	}

	@Id @GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "Prdid", nullable = false)
	public Products getProducts() {
		return this.products;
	}

	public void setProducts(Products products) {
		this.products = products;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "Ckid", nullable = false)
	public Chuku getChuku() {
		return this.chuku;
	}

	public void setChuku(Chuku chuku) {
		this.chuku = chuku;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "Sid", nullable = false)
	public Specifications getSpecifications() {
		return this.specifications;
	}

	public void setSpecifications(Specifications specifications) {
		this.specifications = specifications;
	}

	@Column(name = "Pch", nullable = false, length = 20)
	public String getPch() {
		return this.pch;
	}

	public void setPch(String pch) {
		this.pch = pch;
	}

	@Column(name = "Number", nullable = false)
	public int getNumber() {
		return this.number;
	}

	public void setNumber(int number) {
		this.number = number;
	}
	
	@Column(name = "Status", length = 1)
	public byte getStatus() {
		return status;
	}

	public void setStatus(byte status) {
		this.status = status;
	}

}
