package com.dcsh.market;

// Generated 2009-3-2 20:48:10 by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Custom generated by hbm2java
 */
@Entity
@Table(name = "Custom", schema = "dbo", catalog = "test")
public class Custom implements java.io.Serializable {

	private int id;
	private String customName;
	private String shdz;
	private String phone;
	private Set<Chuku> chukus = new HashSet<Chuku>(0);

	public Custom() {
	}
	
	public Custom(int id) {
		super();
		this.id = id;
	}

	public Custom(int id, String customName, String shdz) {
		this.id = id;
		this.customName = customName;
		this.shdz = shdz;
	}
	
	public Custom(String customName, String shdz, String phone) {
		super();
		this.customName = customName;
		this.shdz = shdz;
		this.phone = phone;
	}

	public Custom(String customName, String shdz) {
		this.customName = customName;
		this.shdz = shdz;
	}

	public Custom(int id, String customName, String shdz, String phone,
			Set<Chuku> chukus) {
		this.id = id;
		this.customName = customName;
		this.shdz = shdz;
		this.phone = phone;
		this.chukus = chukus;
	}
	
	public Custom(int id, String customName, String shdz, String phone) {
		super();
		this.id = id;
		this.customName = customName;
		this.shdz = shdz;
		this.phone = phone;
	}

	@Id @GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "CustomName", nullable = false, length = 50)
	public String getCustomName() {
		return this.customName;
	}

	public void setCustomName(String customName) {
		this.customName = customName;
	}

	@Column(name = "Shdz", nullable = false, length = 100)
	public String getShdz() {
		return this.shdz;
	}

	public void setShdz(String shdz) {
		this.shdz = shdz;
	}

	@Column(name = "Phone", length = 20)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "custom")
	public Set<Chuku> getChukus() {
		return this.chukus;
	}

	public void setChukus(Set<Chuku> chukus) {
		this.chukus = chukus;
	}

}
