package com.dcsh.market;

// Generated 2009-3-2 20:48:10 by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * KcxxId generated by hbm2java
 */
@Embeddable
public class KcxxId implements java.io.Serializable {

	private int pid;
	private String pch;
	private int cid;

	public KcxxId() {
	}

	public KcxxId(int pid, String pch, int cid) {
		this.pid = pid;
		this.pch = pch;
		this.cid = cid;
	}

	@Column(name = "PID", nullable = false)
	public int getPid() {
		return this.pid;
	}

	public void setPid(int pid) {
		this.pid = pid;
	}

	@Column(name = "CID", nullable = false)
	public int getCid() {
		return this.cid;
	}

	public void setCid(int cid) {
		this.cid = cid;
	}

	@Column(name = "Pch", nullable = false, length = 9)
	public String getPch() {
		return this.pch;
	}

	public void setPch(String pch) {
		this.pch = pch;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof KcxxId))
			return false;
		KcxxId castOther = (KcxxId) other;

		return (this.getPid() == castOther.getPid()) && (this.getCid() == castOther.getCid())
				&& ((this.getPch() == castOther.getPch()) || (this.getPch() != null
						&& castOther.getPch() != null && this.getPch().equals(
						castOther.getPch())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPid() * 11 + this.getCid();
		result = 37 * result
				+ (getPch() == null ? 0 : this.getPch().hashCode());
		return result;
	}

}
