package com.dcsh.market;

// Generated 2009-3-2 20:48:10 by Hibernate Tools 3.2.2.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Kcxx generated by hbm2java
 */
@Entity
@Table(name = "Kcxx", schema = "dbo", catalog = "test")
public class Kcxx implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5559441790407690461L;
	private KcxxId id;
	private Specifications specifications;
	private Products products;
	private int number;
	private byte saleType;
	private byte status;
	private String memo;

	public Kcxx() {
	}

	public Kcxx(Specifications specifications, Products products,
			int number,byte saleType, byte status, String memo) {
		this.specifications = specifications;
		this.products = products;
		this.number = number;
		this.saleType = saleType;
		this.status = status;
		this.memo = memo;
	}

	public Kcxx(KcxxId id, Specifications specifications, Products products,
			int number,byte saleType, byte status, String memo) {
		this.id = id;
		this.specifications = specifications;
		this.products = products;
		this.number = number;
		this.saleType = saleType;
		this.status = status;
		this.memo = memo;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "pid", column = @Column(name = "PID", nullable = false)),
			@AttributeOverride(name = "pch", column = @Column(name = "Pch", nullable = false, length = 20)), 
			@AttributeOverride(name = "cid", column = @Column(name = "CID", nullable = false))})
	public KcxxId getId() {
		return this.id;
	}

	public void setId(KcxxId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "SID", nullable = false)
	public Specifications getSpecifications() {
		return this.specifications;
	}

	public void setSpecifications(Specifications specifications) {
		this.specifications = specifications;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "PID", nullable = false, insertable = false, updatable = false)
	public Products getProducts() {
		return this.products;
	}

	public void setProducts(Products products) {
		this.products = products;
	}

	@Column(name = "Number", nullable = false)
	public int getNumber() {
		return this.number;
	}

	public void setNumber(int number) {
		this.number = number;
	}
	@Column(name = "SaleType", nullable = false)
	public byte getSaleType() {
		return this.saleType;
	}

	public void setSaleType(byte saleType) {
		this.saleType = saleType;
	}

	@Column(name = "Status", nullable = false)
	public byte getStatus() {
		return this.status;
	}

	public void setStatus(byte status) {
		this.status = status;
	}

	@Column(name = "memo", length = 100)
	public String getMemo() {
		return memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	/*
	 * 入库的数量
	 */
	public void entryNumber(int number){
		this.number += number;
	}
}
