package com.dcsh.market;

// Generated 2009-3-2 20:48:10 by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "Users", schema = "dbo", catalog = "test")
public class Users implements java.io.Serializable {

	private int id;
	private String name;
	private byte[] password;
	private String description;
	private String phone;

	private Set<UserGroup> group = new HashSet<UserGroup>(0);



	public Users() {
	}

	public Users(int id) {
		this.id = id;
	}

	public Users(int id, String name, byte[] password, String desc) {
		this.id = id;
		this.name = name;
		this.password = password;
		this.description = desc;
	}

	public Users(String name, byte[] password, String desc) {

		this.name = name;
		this.password = password;
		this.description = desc;
	}
	
	

	public Users(String name, byte[] password, String description, String phone) {
		super();
		this.name = name;
		this.password = password;
		this.description = description;
		this.phone = phone;
	}

	public Users(int id, String name, byte[] password, String description,
			String phone) {
		super();
		this.id = id;
		this.name = name;
		this.password = password;
		this.description = description;
		this.phone = phone;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "Name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Password", length = 50)
	public byte[] getPassword() {
		return this.password;
	}

	public void setPassword(byte[] password) {
		this.password = password;
	}

	@Column(name = "Description", length = 100)
	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}


	@ManyToMany(targetEntity = UserGroup.class)
	@JoinTable(name = "UserRelGroup", joinColumns = @JoinColumn(name = "UID"), inverseJoinColumns = @JoinColumn(name = "GID"))
	public Set<UserGroup> getGroup() {
		return group;
	}

	public void setGroup(Set<UserGroup> group) {
		this.group = group;
	}


	@Column(name = "Phone", length = 11)
	public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}
	
    public int hashCode() {
    	return this.getId();
    }
    
    @Override
    public boolean equals(Object obj){
    	if(obj instanceof Users){
    		Users users = (Users)obj;
    		return this.getId() == users.getId();
    	}
    	return false;
    }
	

}
